### ISSUE TITLE
Handle TODOs for upload/download bot

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/chat-copilot#47]
```[tasklist]
### Tasks
- [ ] Test Upload a bot in SimplifiedNewBotMenu
- [ ] Add loading indicators on download bot
- [ ] Add strong typing
- [ ] Change from MemoryQueryResult to MemoryRecord
- [x] Address TODOs in BotController
```

**Comment by crickman** [comment]
This has come within the scope of semantic-memory integration.
