### ISSUE TITLE
[Custom Plugins] Validate OpenAPI spec on entry

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/chat-copilot#76]
In the Custom Plugin flow on the webapp, we need to form validation to verify the Open API spec once it's parsed from the manifest file. 

![Image](https://github.com/microsoft/chat-copilot/assets/125500434/bb258d83-4721-4a45-8335-ce0e9f3d0314)

I'm thinking we expose an API from the webapi that calls the OpenAPI parser to validate the form and then call that from the webapp
```[tasklist]
### Tasks
- [ ] Add Open API Spec verification (see PluginUtils.ts)
- [ ] Add manifest details to ValidateStep
- [ ] Add error handling if plugin isn't validated
```

**Comment by teresaqhoang** [comment]
Continuation of another issue-- see TODOs tagged: [1973](https://github.com/microsoft/semantic-kernel/issues/1973)
