### ISSUE TITLE
Planner Enhancements

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/chat-copilot#93]
Need to re-evaluate our ExternalInformationSkill to better support SequentialPlanner inputs and outputs
```[tasklist]
### Tasks
- [ ] Allow user to delete inputs (webapp) + flag inputs as required or not
- [ ] Add dropdown of suggested values from available outputs in PlanStepInput (webapp)
- [ ] Parse all variables from plan's result context if executed successfully (may include cumulative results between steps if using SequentialPlanner)
- [ ] Add context into RelatedInformation section of steps successfully executed? with Goal plan fulfilled
- [ ] Save Plan results as embeddings?
```

**Comment by teresaqhoang** [comment]
Save Plan results as embeddings so it doesn't call the same API twice


![Image](https://github.com/microsoft/chat-copilot/assets/125500434/b7c1fdbf-43a3-4957-ac89-14f286acfbc0)

![Image](https://github.com/microsoft/chat-copilot/assets/125500434/1f8ca47c-7be8-4ec9-acf5-826e9b04b3a2)
